

# local
# spring:
#   datasource:
#     driver-class-name: org.mariadb.jdbc.Driver
#     url: jdbc:mariadb://localhost:3306/stocktest
#     username: root
#     password: 1234

spring:
  messages:
    encoding: UTF-8

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
    redis:
      host: 127.0.0.1
      port: 6379




  # encoding
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true


# redis


# File Info
file:
  upload-dir: IPO/
# spring:
#   servlet:
#     multipart:
#       max-request-size: 100MB

# AWS_S3 Access
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}


    # AWS S3 bucket Info
    s3:
      bucket: dhblogbucket

    region:
      static: ap-northeast-2
    stack:
      auto: false

# Extension
# default:
#   image:
#     extension: .jpg
#   video:
#     extension: .mp4
#   file:
#     extension: .txt

logging:
  level:
    org:
      modelmapper: DEBUG
    api:
      stock:
        stock: DEBUG



secretKey: ${SECRET_KEY}